CREATE TABLE "HR"."APTEKI2"    
   ( "APTEKI" VARCHAR2(255 BYTE), 
 "APTEKA_NUMBER" VARCHAR2(26 BYTE), 
 "APTEKA_NUMBER_URL" VARCHAR2(26 BYTE), 
 "APTEKA_ADDRESS" VARCHAR2(128 BYTE)
   ) ;



  CREATE TABLE "HR"."LEKARSTVA2"    
   ( "MEDICINE_NAME" VARCHAR2(256 BYTE), 
 "MEDICINE_URL" VARCHAR2(256 BYTE), 
 "MEDICINE_PRICE" VARCHAR2(26 BYTE), 
 "MEDICINE_NUMBER" VARCHAR2(26 BYTE)
   )



  CREATE TABLE "HR"."ITEKA_SIGNUP"    
   ( "NAME1" VARCHAR2(60 BYTE), 
 "SURNAME" VARCHAR2(60 BYTE), 
 "CITY" VARCHAR2(60 BYTE), 
 "EMAILL" VARCHAR2(60 BYTE), 
 "MOBILE" NUMBER, 
 "PASSWORD1" VARCHAR2(60 BYTE), 
 "STATUS" VARCHAR2(20 BYTE),
     "ID" NUMBER

   )



  CREATE TABLE "HR"."ITEKA_USERS"    
   ( "NAME" VARCHAR2(60 BYTE), 
 "EMAILL" VARCHAR2(60 BYTE), 
 "PASSWORD" VARCHAR2(60 BYTE), 
 "DAY_OF_L" DATE, 
 "POL" VARCHAR2(60 BYTE), 
 "HEIGHT" VARCHAR2(60 BYTE), 
 "WEIGHT" VARCHAR2(60 BYTE), 
 "CITY" VARCHAR2(60 BYTE),     
"ID" NUMBER

   )






 CREATE TABLE "HR"."KAYRIMDILIK"                 
   ( "NAME_K" VARCHAR2(100 BYTE), 
 "NAME" VARCHAR2(60 BYTE), 
 "EMAILL" VARCHAR2(60 BYTE), 
 "SROK_K" VARCHAR2(60 BYTE), 
 "ID2" TIMESTAMP (6) DEFAULT sysdate, 
 "NUMBER_YOUR" VARCHAR2(60 BYTE),
    "ID" Number
   )



  CREATE TABLE "HR"."TABLE_REG"                     
   ( "APTEKI" VARCHAR2(250 BYTE), 
 "APTEKA_ADDRESS" VARCHAR2(250 BYTE), 
 "APTEKA_NUMBER" VARCHAR2(250 BYTE), 
 "APTEKA_NUMBER_URL" VARCHAR2(250 BYTE),
     "ID" Number
   )


  CREATE TABLE "HR"."ITEKA_ANALYZES" 
   ( "EMAILL" VARCHAR2(60 BYTE), 
 "PASSWORD" VARCHAR2(60 BYTE), 
 "NAME_OF_AN" VARCHAR2(60 BYTE), 
 "START_DATE" VARCHAR2(60 BYTE), 
 "END_DATE" VARCHAR2(60 BYTE), 
 "ID2" TIMESTAMP (6) DEFAULT sysdate,
"ID" Number
   )




 CREATE TABLE "HR"."ITEKA_APTEKA_TOLTIRU" 
   ( "NAME_DARY" VARCHAR2(90 BYTE), 
 "NUMBERR_DARY" VARCHAR2(90 BYTE), 
 "START_DATE" VARCHAR2(90 BYTE), 
 "END_DATE" VARCHAR2(90 BYTE), 
 "USER_ROWW" VARCHAR2(92 BYTE), 
 "HIRE_DATE" TIMESTAMP (6) DEFAULT SYSDATE, 
 "ID1" NVARCHAR2(90),"ID" Number
   )
 




  CREATE TABLE "HR"."ITEKA_DIAGNOS" 
   ( "EMAILL" VARCHAR2(60 BYTE), 
 "PASSWORD" VARCHAR2(60 BYTE), 
 "NAME_OF_D" VARCHAR2(60 BYTE), 
 "TYPE" VARCHAR2(60 BYTE), 
 "START_DATE" VARCHAR2(60 BYTE), 
 "END_DATE" VARCHAR2(60 BYTE), 
 "NAME_DARY" VARCHAR2(60 BYTE), 
 "DIETS" VARCHAR2(60 BYTE), 
 "REJIM_LECHENYA" VARCHAR2(60 BYTE), 
 "NOTES" VARCHAR2(60 BYTE), 
 "ID2" TIMESTAMP (6) DEFAULT sysdate,
    "ID" Number
   )





  CREATE TABLE "HR"."ITEKA_DOCTORS_USER"   
   ( "NAME" VARCHAR2(60 BYTE), 
 "START_DATE" VARCHAR2(60 BYTE), 
 "ADRESS" VARCHAR2(60 BYTE), 
 "CLOCK1" VARCHAR2(60 BYTE), 
 "TYPE1" VARCHAR2(60 BYTE), 
 "EMAILL" VARCHAR2(60 BYTE), 
 "PASSWORD" VARCHAR2(60 BYTE), 
 "ID2" TIMESTAMP (6) DEFAULT sysdate
    ,"ID" number
   )